// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repositories

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Activity struct {
	ID           int32
	CreatedAt    pgtype.Timestamptz
	UserID       pgtype.UUID
	Distance     pgtype.Numeric
	ActivityName string
	AvgSpeed     pgtype.Numeric
	MaxSpeed     pgtype.Numeric
	ElapsedTime  pgtype.Time
	TotalTime    pgtype.Time
}

type Record struct {
	ID               int32
	TimeStamp        pgtype.Timestamptz
	Position         pgtype.Point
	Altitude         pgtype.Int4
	HeartRate        pgtype.Int2
	Cadence          pgtype.Int2
	Distance         pgtype.Int4
	Speed            pgtype.Int4
	Temperature      pgtype.Int2
	GpsAccuracy      pgtype.Int2
	EnhancedAltitude pgtype.Int4
	ActivityID       pgtype.Int4
}
