ALTER TABLE activities ADD COLUMN IF NOT EXISTS activity_name  varchar(255) NOT NULL;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS activity_name  varchar(255) NOT NULL;

ALTER TABLE activities ADD COLUMN IF NOT EXISTS avg_speed  NUMERIC NOT NULL;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS max_speed  NUMERIC NOT NULL;

ALTER TABLE activities ADD COLUMN IF NOT EXISTS elapsed_time TIME NOT NULL;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS total_time TIME NOT NULL;

ALTER TABLE activities ADD COLUMN IF NOT EXISTS distance NUMERIC NOT NULL;
