ALTER TABLE activities 
ADD COLUMN IF NOT EXISTS weather_impact  NUMERIC(5,2) NOT NULL DEFAULT 0;

ALTER TABLE activities 
ADD COLUMN IF NOT EXISTS headwind INTEGER NOT NULL;

ALTER TABLE activities 
ADD COLUMN IF NOT EXISTS longest_headwind time NOT NULL;

ALTER TABLE activities 
ADD COLUMN IF NOT EXISTS air_speed  NUMERIC(6,2) NOT NULL;

ALTER TABLE activities 
ADD COLUMN IF NOT EXISTS temp  NUMERIC(5,2) NOT NULL;

ALTER TABLE records
ADD COLUMN IF NOT EXISTS bearing DOUBLE PRECISION NOT NULL;