// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: media.sql

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CreateMediaParams struct {
	Location   pgtype.Text `json:"location"`
	ActivityID pgtype.Int4 `json:"activityId"`
	UserID     string      `json:"userId"`
}
