// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Activity struct {
	ID             int32              `json:"id"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	DateOfActivity pgtype.Timestamptz `json:"dateOfActivity"`
	UserID         string             `json:"userId"`
	Centroid       pgtype.Point       `json:"centroid"`
	Distance       decimal.Decimal    `json:"distance"`
	ActivityName   string             `json:"activityName"`
	AvgSpeed       decimal.Decimal    `json:"avgSpeed"`
	MaxSpeed       decimal.Decimal    `json:"maxSpeed"`
	ElapsedTime    time.Time          `json:"elapsedTime"`
	TotalTime      time.Time          `json:"totalTime"`
}

type ActivityWithRecordsView struct {
	ID              int32              `json:"id"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UserID          string             `json:"userId"`
	Distance        decimal.Decimal    `json:"distance"`
	ActivityName    string             `json:"activityName"`
	AvgSpeed        decimal.Decimal    `json:"avgSpeed"`
	MaxSpeed        decimal.Decimal    `json:"maxSpeed"`
	ElapsedTime     time.Time          `json:"elapsedTime"`
	TotalTime       time.Time          `json:"totalTime"`
	ElapsedTimeChar string             `json:"elapsedTimeChar"`
	TotalTimeChar   string             `json:"totalTimeChar"`
	Records         []Record           `json:"records"`
}

type Record struct {
	ID               int32              `json:"id"`
	TimeStamp        pgtype.Timestamptz `json:"timeStamp"`
	Position         pgtype.Point       `json:"position"`
	Altitude         pgtype.Int4        `json:"altitude"`
	HeartRate        pgtype.Int2        `json:"heartRate"`
	Cadence          pgtype.Int2        `json:"cadence"`
	Distance         pgtype.Int4        `json:"distance"`
	Speed            pgtype.Int4        `json:"speed"`
	Temperature      pgtype.Int2        `json:"temperature"`
	GpsAccuracy      pgtype.Int2        `json:"gpsAccuracy"`
	EnhancedAltitude pgtype.Int4        `json:"enhancedAltitude"`
	ActivityID       pgtype.Int4        `json:"activityId"`
}
