// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Activity struct {
	ID              int32              `json:"id"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	DateOfActivity  pgtype.Timestamptz `json:"dateOfActivity"`
	UserID          string             `json:"userId"`
	Centroid        pgtype.Point       `json:"centroid"`
	Distance        decimal.Decimal    `json:"distance"`
	ActivityName    string             `json:"activityName"`
	AvgSpeed        decimal.Decimal    `json:"avgSpeed"`
	MaxSpeed        decimal.Decimal    `json:"maxSpeed"`
	RideType        string             `json:"rideType"`
	ElapsedTime     time.Duration      `json:"elapsedTime"`
	TotalTime       time.Duration      `json:"totalTime"`
	WeatherImpact   decimal.Decimal    `json:"weatherImpact"`
	Headwind        int32              `json:"headwind"`
	LongestHeadwind time.Time          `json:"longestHeadwind"`
	AirSpeed        decimal.Decimal    `json:"airSpeed"`
	Temp            decimal.Decimal    `json:"temp"`
}

type ActivityWithRecordsView struct {
	ID              int32              `json:"id"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UserID          string             `json:"userId"`
	Distance        decimal.Decimal    `json:"distance"`
	ActivityName    string             `json:"activityName"`
	AvgSpeed        decimal.Decimal    `json:"avgSpeed"`
	MaxSpeed        decimal.Decimal    `json:"maxSpeed"`
	RideType        string             `json:"rideType"`
	ElapsedTime     time.Duration      `json:"elapsedTime"`
	TotalTime       time.Duration      `json:"totalTime"`
	ElapsedTimeChar string             `json:"elapsedTimeChar"`
	TotalTimeChar   string             `json:"totalTimeChar"`
	Records         []Record           `json:"records"`
}

type Record struct {
	ID               int32              `json:"id"`
	TimeStamp        pgtype.Timestamptz `json:"timeStamp"`
	Position         pgtype.Point       `json:"position"`
	Altitude         pgtype.Int4        `json:"altitude"`
	HeartRate        pgtype.Int2        `json:"heart_rate"`
	Cadence          pgtype.Int2        `json:"cadence"`
	Distance         pgtype.Int4        `json:"distance"`
	Speed            pgtype.Int4        `json:"speed"`
	Temperature      pgtype.Int2        `json:"temperature"`
	GpsAccuracy      pgtype.Int2        `json:"gpsAccuracy"`
	EnhancedAltitude pgtype.Int4        `json:"enhancedAltitude"`
	ActivityID       pgtype.Int4        `json:"activityId"`
	Bearing          float64            `json:"bearing"`
}
