name: Build Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'
  workflow_dispatch:

jobs:
  backend-test:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
        - name: Setup Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.21.x'
        - name: Install dependencies
          run: go get .
        - name: Test with the Go CLI
          run: go test ./backend/**


  backend-build:
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, 'backend/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          ls -al 
          docker build -t ${{ secrets.DOCKER_USERNAME }}/velovoyager-backend:${IMAGE_TAG} -f backend/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/velovoyager-backend:${IMAGE_TAG}
          docker tag ${{ secrets.DOCKER_USERNAME }}/velovoyager-backend:${IMAGE_TAG} ${{ secrets.DOCKER_USERNAME }}/velovoyager-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/velovoyager-backend:latest
  frontend-build:
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, 'frontend/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend Docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/velovoyager-frontend:${IMAGE_TAG} -f frontend/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/velovoyager-frontend:${IMAGE_TAG}
          docker tag ${{ secrets.DOCKER_USERNAME }}/velovoyager-frontend:${IMAGE_TAG} ${{ secrets.DOCKER_USERNAME }}/velovoyager-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/velovoyager-frontend:latest
